# Use NodeJS on flexible app engine
runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

entrypoint: node server.js  # Start your Express server

handlers:  
  - url: /socket.io/.*
    script: auto  # Ensure the socket.io path is handled correctly
    
  - url: /css
    static_dir: dist/css

  - url: /js
    static_dir: dist/js

  - url: /img
    static_dir: dist/img

  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html